<!--
/**
* Copyright © Vitor Morais, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
 -->

<?php
    $viewModel = $block->getData('viewModel');
    $openNewTab = $viewModel->getOpenNewTab();
    $whatsappNumber = $viewModel->getWhatsAppNumber();
    $whatsappMessage = $viewModel->getWhatsappMessage();
    $urlWhatsapp = $viewModel->getWhatsappUrlApi();
?>

<?php if (!empty($whatsappNumber)): ?>
     <div class="whatsapp-fixed <?= $viewModel->getWhatsappPosition() ?>">
          <a href="<?= $urlWhatsapp ?><?= $whatsappNumber ?><?= $whatsappMessage ?>"
               rel="noopener"
               aria-label="WhatsApp"
               target="<?= $openNewTab ? '_blank' : '_self';?>">
               <img
                    src="<?php echo $this->getViewFileUrl('Vitormorais_Whatsapp::images/wpp-logo.png'); ?>"
                    alt="WhatsApp"
                    title="WhatsApp"
                    loading="lazy"
               >
          </a>
     </div>
<?php endif; ?>